### ISSUE TITLE
Does this display actual .pdf docs, or just html?

### ISSUE THREAD

**Issue by devxpy** [Rockvole/pdfview#2]

**Comment by Rockvole** [comment]
It generates and displays a pdf from html.

**Comment by devxpy** [comment]
Does that mean I can show a PDF document from a file? If you use the system's PDF viewer, can you please share how one can launch it using a PDF file?

**Comment by Rockvole** [comment]
My code converts html (or plain text) into pdf format and displays it inside the android pdf viewer.
All the code for that can be seen here :
https://github.com/Rockvole/pdfview/blob/master/android/src/main/java/com/rockvole/pdfview/PdfviewPlugin.java

If you want to display a pdf you can do that by using some standard flutter classes, e.g :

    new RichText(
      text: new LinkTextSpan(
          url: 'http://docs.google.com/viewer?url=http://www.pdf995.com/samples/pdf.pdf',
          text: 'Show My Pdf'),
    ),

This is the LinkTextSpan class :

    class LinkTextSpan extends TextSpan {
      LinkTextSpan({TextStyle style, String url, String text})
          : super(
          style: style,
          text: text ?? url,
          recognizer: new TapGestureRecognizer()
            ..onTap = () {
              launch(url);
            });
    }

**Comment by devxpy** [comment]
Got it. Thanks.

The title was a bit misleading, that's all.

**Comment by eugenio-tesio** [comment]
The launch(url) method is giving me an error, what do i have to import?
```
class LinkTextSpan extends TextSpan {
  LinkTextSpan({TextStyle style, String url, String text})
      : super(
      style: style,
      text: text ?? url,
      recognizer: new TapGestureRecognizer()
        ..onTap = () {
          launch(url);
        });
}
```

**Comment by Rockvole** [comment]
In pubspec.yaml you need :

      url_launcher: ^0.4.2+5

The include is :

    import 'package:flutter/src/gestures/tap.dart';
    import 'package:url_launcher/url_launcher.dart';
